<?php

$tp['database'] = array();
$tp['database']["TP_WEBSITE_WRITE"] = array();
$tp['database']["TP_WEBSITE_WRITE"]["host"] = '127.0.0.1';
$tp['database']["TP_WEBSITE_WRITE"]["pers"] = 0;
$tp['database']["TP_WEBSITE_WRITE"]["port"] = "3306";
$tp['database']["TP_WEBSITE_WRITE"]["user"] = 'root';
$tp['database']["TP_WEBSITE_WRITE"]["pass"] = '';
$tp['database']["TP_WEBSITE_WRITE"]["name"] = 'newdata';
$tp['database']["TP_WEBSITE_WRITE"]["pref"] = "";
$tp['database']["TP_WEBSITE_WRITE"]["char"] = "utf8";
$tp['database']["TP_WEBSITE_WRITE"]["endc"] = "\r\n";
$tp['database']["TP_WEBSITE_WRITE"]["type"] = "mysql";
$tp['database']["TP_WEBSITE_WRITE"]["shar"] = true;

$tp['database']["TP_WEBSITE_READ"] = array();
$tp['database']["TP_WEBSITE_READ"]["host"] = '127.0.0.1';
$tp['database']["TP_WEBSITE_READ"]["pers"] = 0;
$tp['database']["TP_WEBSITE_READ"]["port"] = "3306";
$tp['database']["TP_WEBSITE_READ"]["user"] = 'root';
$tp['database']["TP_WEBSITE_READ"]["pass"] = '';
$tp['database']["TP_WEBSITE_READ"]["name"] = 'newdata';
$tp['database']["TP_WEBSITE_READ"]["pref"] = "";
$tp['database']["TP_WEBSITE_READ"]["char"] = "utf8";
$tp['database']["TP_WEBSITE_READ"]["endc"] = "\r\n";
$tp['database']["TP_WEBSITE_READ"]["type"] = "mysql";
$tp['database']["TP_WEBSITE_READ"]["shar"] = true;

?>